---
title: "Final Project"
author: "Christian Guaraca"
output:
  pdf_document: default
  html_document: default
---

```{r}
#import housing_data 
housing_data = read.csv(file = '/Applications/MAT 342/housing_data.csv')
```


```{r}
#load packages
pacman::p_load(tidyverse, mlr, mlr3, missForest, skimr, rpart, randomForest, data.table, dplyr, magrittr, rpart.plot)
```

```{r}
#picking certain data that does not apply in my opinion
housing_data_select = housing_data %>% 
  select(approx_year_built, cats_allowed, coop_condo, dogs_allowed, dining_room_type, fuel_type,
         garage_exists, kitchen_type, maintenance_cost, num_bedrooms, num_floors_in_building,
         num_full_bathrooms, num_total_rooms, parking_charges, sale_price, sq_footage, total_taxes, walk_score)
```

```{r}
setDT (housing_data_select)
```

```{r}
dim(housing_data_select)
str(housing_data_select)
```

```{r} 
#removing any data with excessive NA
housing_data_drop = housing_data_select %>%
  select(-parking_charges, -sq_footage, -total_taxes, -num_floors_in_building) 
```

```{r}
#Adjusting the features so they can be used to run the algorithms
housing_data_new = housing_data_drop %>% 
  mutate(cats_allowed = ifelse(cats_allowed == "yes", 1, 0)) %>% #set data to binary
  mutate(dogs_allowed = ifelse(dogs_allowed == "yes", 1, 0)) %>% #set data to binary 
  mutate(maintenance_cost = as.numeric(gsub('[$,]', '', housing_data_drop$maintenance_cost))) %>% #remove $ and , from obs
  mutate(sale_price = as.numeric(gsub('[$,]', '', housing_data_drop$sale_price))) %>% #remove $ and , from obs
  mutate(coop_condo = factor(coop_condo, ordered = FALSE)) %>%
  mutate(dining_room_type = factor(dining_room_type, ordered = FALSE)) %>%
  mutate(fuel_type = factor(fuel_type, ordered = FALSE)) %>%
  mutate(kitchen_type = factor(kitchen_type, ordered = FALSE)) %>%
  mutate(garage_exists = ifelse(is.na(garage_exists), 0, 1)) #making sure NA is turned to 0
```


```{r}
housing_data_new %>% 
  filter(!is.na(sale_price))
```

```{r}
missing_data = tbl_df(apply(is.na(housing_data_new), 2, as.numeric))
colnames(missing_data) = paste("missing_data_", colnames(housing_data_new), sep = "")
missing_data %<>% 
  select_if(function(x){sum(x) > 0})
housing_imp = missForest(data.frame(housing_data_new))$ximp
housing = cbind(housing_imp,missing_data)
```

```{r}
#making train and test split
test_prop = 0.1

#test
test_indices = sample(1:nrow(housing), round((test_prop)*nrow(housing)))
housing_test = housing[test_indices,]
y_test = housing_test$sale_price
X_test = cbind(1, housing_test)
X_test$sale_price = NULL

#train
train_indices = setdiff(1:nrow(housing), test_indices)
housing_train = housing[train_indices,]
y_train = housing_train$sale_price
X_train = cbind(1, housing_train)
X_train$sale_price = NULL
n_train = nrow(X_train)

```

```{r}
#Create Regression tree model

#use rpart, YARF not availible for me
#In-sample Error
Reg_tree = rpart(y_train~., housing_train)
y_hat_train = predict(Reg_tree, housing_train)
e_in = y_train - y_hat_train
rsme_in = sd(e_in)
r_squared_in = (var(y_train)-var(e_in)) / var(y_train)

#OOSE
y_hat_test = predict(Reg_tree, housing_test)
e_oose = y_test - y_hat_test
rsme_oose = sd(e_oose)
rsquared_oose = (var(y_test) - var(e_oose)) / var(y_test)

```

```{r}
fit_model = rpart(housing_train$sale_price~., data.frame(X_train), method="anova")
rpart.plot(fit_model)
fit_model
```

```{r eval=FALSE}
#mlr attempt
mod_task = makeRegrTask(data = data.frame(X_train), target = 'housing_data$sale_price')
algor = makeLearner("regr.rpart")
valid = makeResampleDesc("CV", iteration = 5)
resample = resample(algor, mod_task, valid, measures = list(rmse))
resample
mean(resample$measures.test$rmse)
```

```{r}
#Random Forest
random_forest = randomForest(sale_price~.,housing_imp)
random_forest

```





